const EOK=100000000,JO=10000*EOK;
const defaults={memoryPeople:27400,lsiPeople:20900,commonPeople:29000,operatingProfitJo:100,fundRatio:10,divisionRatio:40,taxableRatio:100};
const s={...defaults};
const brackets=[{l:14000000,r:.06,d:0},{l:50000000,r:.15,d:1260000},{l:88000000,r:.24,d:5760000},{l:150000000,r:.35,d:15440000},{l:300000000,r:.38,d:19940000},{l:500000000,r:.40,d:25940000},{l:1000000000,r:.42,d:35940000},{l:Infinity,r:.45,d:65940000}];
function clamp(v,min,max){v=Number(v);return Number.isNaN(v)?min:Math.min(max,Math.max(min,v))}
function krw(v){if(v>=JO)return (v/JO).toLocaleString('ko-KR',{maximumFractionDigits:2})+'조원';if(v>=EOK)return (v/EOK).toLocaleString('ko-KR',{maximumFractionDigits:2})+'억원';return Math.round(v/10000).toLocaleString('ko-KR')+'만원'}
function man(v){return Math.round(v/10000).toLocaleString('ko-KR')+'만원'}
function tax(income){const b=brackets.find(x=>income<=x.l);const n=Math.max(0,income*b.r-b.d);return{national:n,local:n*.1,total:n*1.1,rate:b.r}}
function slider(key,label,min,max,step,suffix,help){return `<div class="panel"><div class="row"><div><div class="label">${label}</div><div class="help" id="h-${key}">${help||''}</div></div><div class="num"><input id="n-${key}" type="number" min="${min}" max="${max}" step="${step}" value="${s[key]}" oninput="setVal('${key}',this.value,${min},${max})"><span>${suffix}</span></div></div><input id="r-${key}" type="range" min="${min}" max="${max}" step="${step}" value="${s[key]}" oninput="setVal('${key}',this.value,${min},${max})"><div class="minmax"><span>${min.toLocaleString('ko-KR')}${suffix}</span><span>${max.toLocaleString('ko-KR')}${suffix}</span></div></div>`}
function build(){document.getElementById('controls').innerHTML=[slider('operatingProfitJo','영업이익',1,500,1,'조','1조 ~ 500조'),slider('fundRatio','성과급 재원비율',1,100,.5,'%','0.5% 단위'),slider('divisionRatio','부문 비율',0,100,10,'%','현재 부문:사업부 = 4:6'),slider('taxableRatio','과세 반영률',0,100,5,'%','성과급 전액 과세 가정이면 100%'),slider('memoryPeople','메모리 인원',1,100000,100,'명',''),slider('lsiPeople','LSI/파운드리 인원',1,100000,100,'명',''),slider('commonPeople','공통사업부 인원',1,100000,100,'명','')].join('')}
function setVal(k,v,min,max){s[k]=clamp(v,min,max);document.getElementById('n-'+k).value=s[k];document.getElementById('r-'+k).value=s[k];render()}
function resetAll(){Object.assign(s,defaults);for(const k in s){let n=document.getElementById('n-'+k),r=document.getElementById('r-'+k);if(n)n.value=s[k];if(r)r.value=s[k]}render()}
function card(title,year,people,gross,shared,business,taxableRatio){const t=tax(gross*taxableRatio),net=Math.max(0,gross-t.total),eff=gross?t.total/gross:0,yg=gross/3,yn=net/3;const years=['첫해','두 번째 해','세 번째 해'].map(y=>`<div class="yr"><strong>${y}</strong><div class="amt"><div>세전 ${man(yg)}</div><div class="after">세후 ${man(yn)}</div></div></div>`).join('');return `<div class="card"><div class="head"><div class="people">${people.toLocaleString('ko-KR')}명 기준 · ${year}</div><div class="title">${title}</div></div><div class="body"><div><div class="small">세전 1인 성과급</div><div class="big">${man(gross)}</div><div class="break">공통풀 ${man(shared)} + 사업부풀 ${man(business)}</div></div><div class="tax"><div class="box"><div>종합소득세</div><div>${man(t.national)}</div></div><div class="box"><div>지방소득세</div><div>${man(t.local)}</div></div><div class="box"><div>적용 최고구간</div><div>${Math.round(t.rate*100)}%</div></div><div class="box"><div>실효세율</div><div>${(eff*100).toFixed(1)}%</div></div></div><div class="net"><div class="small">세후 예상 수령액</div><div class="big">${man(net)}</div></div><div class="years"><h3>3년 분할 지급</h3>${years}</div></div></div>`}
function render(){const total=s.memoryPeople+s.lsiPeople+s.commonPeople,totalFund=s.operatingProfitJo*JO*(s.fundRatio/100),sharedPool=totalFund*(s.divisionRatio/100),businessPool=totalFund-sharedPool,shared=total?sharedPool/total:0,memBiz=s.memoryPeople?businessPool/s.memoryPeople:0,mem=shared+memBiz,lsi26=shared,lsi27=lsi26*.6,common=memBiz*.7;document.getElementById('h-divisionRatio').textContent=`현재 부문:사업부 = ${s.divisionRatio/10}:${(100-s.divisionRatio)/10}`;document.getElementById('totalPeople').textContent=total.toLocaleString('ko-KR')+'명';document.getElementById('totalFund').textContent=krw(totalFund);document.getElementById('sharedPool').textContent=krw(sharedPool);document.getElementById('businessPool').textContent=krw(businessPool);document.getElementById('cards').innerHTML=[card('메모리','26년',s.memoryPeople,mem,shared,memBiz,s.taxableRatio/100),card('LSI/파운드리','26년',s.lsiPeople,lsi26,shared,0,s.taxableRatio/100),card('LSI/파운드리','27년',s.lsiPeople,lsi27,lsi27,0,s.taxableRatio/100),card('공통사업부','26년',s.commonPeople,common,0,memBiz*.7,s.taxableRatio/100)].join('')}
build();render();