const EOK=100000000,JO=10000*EOK;
const defaults={memoryPeople:27400,commonPeople:29000,foundryPeople:12900,lsiPeople:8000,memoryProfitJo:300,foundryProfitJo:2,lsiProfitJo:0,fundRatio:10.5,taxableRatio:100};
const s={...defaults};
const groups=['memory','common','foundry','lsi'];
const groupLabel={memory:'메모리',common:'공통사업부',foundry:'파운드리',lsi:'LSI'};
const poolOwner={memoryProfit:'memory',foundryProfit:'foundry',lsiProfit:'lsi'};
const poolLabel={memoryProfit:'메모리 흑자풀',foundryProfit:'파운드리 흑자풀',lsiProfit:'LSI 흑자풀'};
const brackets=[{l:14000000,r:.06,d:0},{l:50000000,r:.15,d:1260000},{l:88000000,r:.24,d:5760000},{l:150000000,r:.35,d:15440000},{l:300000000,r:.38,d:19940000},{l:500000000,r:.40,d:25940000},{l:1000000000,r:.42,d:35940000},{l:Infinity,r:.45,d:65940000}];
function clamp(v,min,max){v=Number(v);return Number.isNaN(v)?min:Math.min(max,Math.max(min,v))}
function krw(v){if(v>=JO)return (v/JO).toLocaleString('ko-KR',{maximumFractionDigits:2})+'조원';if(v>=EOK)return (v/EOK).toLocaleString('ko-KR',{maximumFractionDigits:2})+'억원';return Math.round(v/10000).toLocaleString('ko-KR')+'만원'}
function man(v){return Math.round(v/10000).toLocaleString('ko-KR')+'만원'}
function tax(income){const b=brackets.find(x=>income<=x.l);const n=Math.max(0,income*b.r-b.d);return{national:n,local:n*.1,total:n*1.1,rate:b.r}}
function profitByGroup(){return{memory:s.memoryProfitJo,foundry:s.foundryProfitJo,lsi:s.lsiProfitJo}}
function ratioFor(poolKey,target,profits){const owner=poolOwner[poolKey];if(target===owner)return 100;if(target==='common'){const memRatio=owner==='memory'?100:(profits.memory>0?40:24);return memRatio*.7}return profits[target]>0?40:24}
function slider(key,label,min,max,step,suffix,help){return `<div class="panel"><div class="row"><div><div class="label">${label}</div><div class="help">${help||''}</div></div><div class="num"><input id="n-${key}" type="number" min="${min}" max="${max}" step="${step}" value="${s[key]}" oninput="setVal('${key}',this.value,${min},${max})"><span>${suffix}</span></div></div><input id="r-${key}" type="range" min="${min}" max="${max}" step="${step}" value="${s[key]}" oninput="setVal('${key}',this.value,${min},${max})"><div class="minmax"><span>${min.toLocaleString('ko-KR')}${suffix}</span><span>${max.toLocaleString('ko-KR')}${suffix}</span></div></div>`}
function build(){document.getElementById('controls').innerHTML=[slider('memoryProfitJo','메모리 흑자',0,500,1,'조','내 흑자풀 100 / 다른 흑자 사업부 40 / 적자 사업부 24'),slider('foundryProfitJo','파운드리 흑자',0,500,1,'조','공통은 항상 메모리 가중치의 70%'),slider('lsiProfitJo','LSI 흑자',0,500,1,'조','흑자 여부에 따라 가중치 자동 계산'),slider('fundRatio','성과급 재원비율',1,100,.5,'%','각 사업부 흑자에 적용'),slider('taxableRatio','과세 반영률',0,100,5,'%','성과급 전액 과세 가정이면 100%'),slider('memoryPeople','메모리 인원',1,100000,100,'명',''),slider('commonPeople','공통사업부 인원',1,100000,100,'명',''),slider('foundryPeople','파운드리 인원',1,100000,100,'명','기본값 12,900명'),slider('lsiPeople','LSI 인원',1,100000,100,'명','기본값 8,000명')].join('')}
function setVal(k,v,min,max){s[k]=clamp(v,min,max);document.getElementById('n-'+k).value=s[k];document.getElementById('r-'+k).value=s[k];render()}
function resetAll(){Object.assign(s,defaults);for(const k in s){let n=document.getElementById('n-'+k),r=document.getElementById('r-'+k);if(n)n.value=s[k];if(r)r.value=s[k]}render()}
function people(){return{memory:s.memoryPeople,common:s.commonPeople,foundry:s.foundryPeople,lsi:s.lsiPeople}}
function calculate(){const p=people(),profits=profitByGroup(),poolProfits={memoryProfit:s.memoryProfitJo,foundryProfit:s.foundryProfitJo,lsiProfit:s.lsiProfitJo};const result={};groups.forEach(g=>result[g]={gross:0,total:0,details:[]});const pools=[];for(const pk of Object.keys(poolProfits)){const fund=poolProfits[pk]*JO*(s.fundRatio/100),totalWeight=groups.reduce((sum,g)=>sum+ratioFor(pk,g,profits)*p[g],0),unit=totalWeight?fund/totalWeight:0;pools.push({pk,fund,totalWeight,unit});for(const g of groups){const ratio=ratioFor(pk,g,profits),per=unit*ratio,dept=per*p[g];result[g].gross+=per;result[g].total+=dept;result[g].details.push({pk,ratio,per});}}return{p,result,pools,totalPeople:Object.values(p).reduce((a,b)=>a+b,0),totalFund:pools.reduce((a,b)=>a+b.fund,0)}}
function card(g,data){const r=data.result[g],p=data.p[g],t=tax(r.gross*(s.taxableRatio/100)),net=Math.max(0,r.gross-t.total),eff=r.gross?t.total/r.gross:0,yg=r.gross/3,yn=net/3;const detail=r.details.map(d=>`<div class="yr"><strong>${poolLabel[d.pk]} · 비율 ${d.ratio}</strong><div class="amt">${man(d.per)}</div></div>`).join('');const years=['첫해','두 번째 해','세 번째 해'].map(y=>`<div class="yr"><strong>${y}</strong><div class="amt"><div>세전 ${man(yg)}</div><div class="after">세후 ${man(yn)}</div></div></div>`).join('');return `<div class="card"><div class="head"><div class="people">${p.toLocaleString('ko-KR')}명 기준</div><div class="title">${groupLabel[g]}</div></div><div class="body"><div><div class="small">세전 1인 성과급 합계</div><div class="big">${man(r.gross)}</div><div class="break">부서 총액 ${krw(r.total)}</div></div><div class="years"><h3>흑자풀별 1인당 금액</h3>${detail}</div><div class="tax"><div class="box"><div>종합소득세</div><div>${man(t.national)}</div></div><div class="box"><div>지방소득세</div><div>${man(t.local)}</div></div><div class="box"><div>적용 최고구간</div><div>${Math.round(t.rate*100)}%</div></div><div class="box"><div>실효세율</div><div>${(eff*100).toFixed(1)}%</div></div></div><div class="net"><div class="small">세후 예상 수령액</div><div class="big">${man(net)}</div></div><div class="years"><h3>3년 분할 지급</h3>${years}</div></div></div>`}
function render(){const d=calculate();document.getElementById('totalPeople').textContent=d.totalPeople.toLocaleString('ko-KR')+'명';document.getElementById('totalFund').textContent=krw(d.totalFund);document.getElementById('sharedPool').textContent=krw(d.pools.find(x=>x.pk==='memoryProfit')?.fund||0);document.getElementById('businessPool').textContent=krw((d.pools.find(x=>x.pk==='foundryProfit')?.fund||0)+(d.pools.find(x=>x.pk==='lsiProfit')?.fund||0));document.getElementById('cards').innerHTML=groups.map(g=>card(g,d)).join('')}
build();render();