const EOK=100000000,JO=10000*EOK;
const defaults={memoryPeople:27400,lsiPeople:20900,commonPeople:29000,operatingProfitJo:300,fundRatio:10.5,memoryRatio:100,commonRatio:70,lsiRatio2026:40,lsiRatio2027:24,taxableRatio:100};
const s={...defaults};
const brackets=[{l:14000000,r:.06,d:0},{l:50000000,r:.15,d:1260000},{l:88000000,r:.24,d:5760000},{l:150000000,r:.35,d:15440000},{l:300000000,r:.38,d:19940000},{l:500000000,r:.40,d:25940000},{l:1000000000,r:.42,d:35940000},{l:Infinity,r:.45,d:65940000}];
function clamp(v,min,max){v=Number(v);return Number.isNaN(v)?min:Math.min(max,Math.max(min,v))}
function krw(v){if(v>=JO)return (v/JO).toLocaleString('ko-KR',{maximumFractionDigits:2})+'조원';if(v>=EOK)return (v/EOK).toLocaleString('ko-KR',{maximumFractionDigits:2})+'억원';return Math.round(v/10000).toLocaleString('ko-KR')+'만원'}
function man(v){return Math.round(v/10000).toLocaleString('ko-KR')+'만원'}
function tax(income){const b=brackets.find(x=>income<=x.l);const n=Math.max(0,income*b.r-b.d);return{national:n,local:n*.1,total:n*1.1,rate:b.r}}
function slider(key,label,min,max,step,suffix,help){return `<div class="panel"><div class="row"><div><div class="label">${label}</div><div class="help">${help||''}</div></div><div class="num"><input id="n-${key}" type="number" min="${min}" max="${max}" step="${step}" value="${s[key]}" oninput="setVal('${key}',this.value,${min},${max})"><span>${suffix}</span></div></div><input id="r-${key}" type="range" min="${min}" max="${max}" step="${step}" value="${s[key]}" oninput="setVal('${key}',this.value,${min},${max})"><div class="minmax"><span>${min.toLocaleString('ko-KR')}${suffix}</span><span>${max.toLocaleString('ko-KR')}${suffix}</span></div></div>`}
function build(){document.getElementById('controls').innerHTML=[slider('operatingProfitJo','영업이익',1,500,1,'조','1조 ~ 500조'),slider('fundRatio','성과급 재원비율',1,100,.5,'%','0.5% 단위'),slider('memoryRatio','메모리 비율',0,100,1,'','기본값 100'),slider('commonRatio','공통 비율',0,100,1,'','기본값 70'),slider('lsiRatio2026','LSI/파운드리 26년 비율',0,100,1,'','기본값 40'),slider('lsiRatio2027','LSI/파운드리 27년 비율',0,100,1,'','기본값 24'),slider('taxableRatio','과세 반영률',0,100,5,'%','성과급 전액 과세 가정이면 100%'),slider('memoryPeople','메모리 인원',1,100000,100,'명',''),slider('lsiPeople','LSI/파운드리 인원',1,100000,100,'명',''),slider('commonPeople','공통사업부 인원',1,100000,100,'명','')].join('')}
function setVal(k,v,min,max){s[k]=clamp(v,min,max);document.getElementById('n-'+k).value=s[k];document.getElementById('r-'+k).value=s[k];render()}
function resetAll(){Object.assign(s,defaults);for(const k in s){let n=document.getElementById('n-'+k),r=document.getElementById('r-'+k);if(n)n.value=s[k];if(r)r.value=s[k]}render()}
function calcCase(lsiRatio,totalFund){const memoryWeight=s.memoryRatio*s.memoryPeople,commonWeight=s.commonRatio*s.commonPeople,lsiWeight=lsiRatio*s.lsiPeople,totalWeight=memoryWeight+commonWeight+lsiWeight,valuePerWeight=totalWeight?totalFund/totalWeight:0;return{memoryWeight,commonWeight,lsiWeight,totalWeight,valuePerWeight,memoryGross:valuePerWeight*s.memoryRatio,commonGross:valuePerWeight*s.commonRatio,lsiGross:valuePerWeight*lsiRatio,memoryTotal:valuePerWeight*memoryWeight,commonTotal:valuePerWeight*commonWeight,lsiTotal:valuePerWeight*lsiWeight}}
function card(title,year,people,ratio,weight,gross,total,taxableRatio){const t=tax(gross*taxableRatio),net=Math.max(0,gross-t.total),eff=gross?t.total/gross:0,yg=gross/3,yn=net/3;const years=['첫해','두 번째 해','세 번째 해'].map(y=>`<div class="yr"><strong>${y}</strong><div class="amt"><div>세전 ${man(yg)}</div><div class="after">세후 ${man(yn)}</div></div></div>`).join('');return `<div class="card"><div class="head"><div class="people">${people.toLocaleString('ko-KR')}명 기준 · ${year}</div><div class="title">${title}</div></div><div class="body"><div><div class="small">세전 1인 성과급</div><div class="big">${man(gross)}</div><div class="break">비율 ${ratio} · 가중치 ${weight.toLocaleString('ko-KR')} · 부서 총액 ${krw(total)}</div></div><div class="tax"><div class="box"><div>종합소득세</div><div>${man(t.national)}</div></div><div class="box"><div>지방소득세</div><div>${man(t.local)}</div></div><div class="box"><div>적용 최고구간</div><div>${Math.round(t.rate*100)}%</div></div><div class="box"><div>실효세율</div><div>${(eff*100).toFixed(1)}%</div></div></div><div class="net"><div class="small">세후 예상 수령액</div><div class="big">${man(net)}</div></div><div class="years"><h3>3년 분할 지급</h3>${years}</div></div></div>`}
function render(){const totalPeople=s.memoryPeople+s.lsiPeople+s.commonPeople,totalFund=s.operatingProfitJo*JO*(s.fundRatio/100),c26=calcCase(s.lsiRatio2026,totalFund),c27=calcCase(s.lsiRatio2027,totalFund);document.getElementById('totalPeople').textContent=totalPeople.toLocaleString('ko-KR')+'명';document.getElementById('totalFund').textContent=krw(totalFund);document.getElementById('sharedPool').textContent=c26.totalWeight.toLocaleString('ko-KR');document.getElementById('businessPool').textContent=krw(c26.valuePerWeight);document.getElementById('cards').innerHTML=[card('메모리','26년',s.memoryPeople,s.memoryRatio,c26.memoryWeight,c26.memoryGross,c26.memoryTotal,s.taxableRatio/100),card('공통사업부','26년',s.commonPeople,s.commonRatio,c26.commonWeight,c26.commonGross,c26.commonTotal,s.taxableRatio/100),card('LSI/파운드리','26년',s.lsiPeople,s.lsiRatio2026,c26.lsiWeight,c26.lsiGross,c26.lsiTotal,s.taxableRatio/100),card('LSI/파운드리','27년',s.lsiPeople,s.lsiRatio2027,c27.lsiWeight,c27.lsiGross,c27.lsiTotal,s.taxableRatio/100)].join('')}
build();render();